<?php

use Drupal\Core\Render\Markup;

function stripe_payment_page_attachments(array &$attachments) {
  $stripe_publish_key = \Drupal::config('stripe_publish_key.settings')->get('stripe_publish_key');
  $attachments['#attached']['library'][] = 'stripe_payment/stripe';
  //$attachments['#attached']['drupalSettings']['stripe']['publishkey'] = $stripe_publish_key;
}

function stripe_payment_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode'],
  );
  switch ($key) {
    case 'stripe_mail':
      $message['headers']['Content-Type'] = 'text/html';
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = "Thank you for signing up";
      $message['body'][] =  $params['message'];
      break;
  }
}