<?php

use Drupal\Core\Render\Markup;

function stripe_payment_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'stripe_payment/stripe';
}

function stripe_payment_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode'],
  );
  switch ($key) {
    case 'stripe_mail':
      $message['headers']['Content-Type'] = 'text/html';
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['body'] =  $params['message'];
      break;
  }
}