sumome_tools.settings:
  type: config_object
  label: 'SumoMe Tools settings'
  mapping:
    sumome_tools:
      type: mapping
      mapping:
        sumo_site_id:
          type: text
          label: 'SumoMe Site ID:'
